#!/usr/bin/env python3
"""Build the consolidated SerialOS handoff specification and file manifest."""

from __future__ import annotations

import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED = {"MASTER_SPEC.md", "FILE_MANIFEST.md", "VALIDATION_REPORT.md"}
TEXT_SUFFIXES = {".md", ".json", ".yaml", ".yml", ".sql", ".py", ".txt", ".example"}
IGNORED_PARTS = {".git", "node_modules", ".pnpm-store", "__pycache__"}


def is_ignored(path: Path) -> bool:
    return any(part in IGNORED_PARTS for part in path.relative_to(ROOT).parts)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_files() -> list[Path]:
    ordered: list[Path] = []

    for name in ["README.md", "START_HERE.md", "AGENTS.md", "PLANS.md", ".env.example"]:
        path = ROOT / name
        if path.exists():
            ordered.append(path)

    groups = [
        "docs",
        "tasks",
        "prompts",
        ".agents/skills",
        "contracts",
        "db",
        "schemas",
        "examples",
        "evals",
        "scripts",
    ]
    for group in groups:
        base = ROOT / group
        if not base.exists():
            continue
        for path in sorted(base.rglob("*")):
            if not path.is_file() or is_ignored(path) or path.name in GENERATED:
                continue
            if path.suffix.lower() in TEXT_SUFFIXES or path.name.endswith(".example"):
                ordered.append(path)

    # Preserve order while protecting against accidental duplicates.
    seen: set[Path] = set()
    return [path for path in ordered if not (path in seen or seen.add(path))]


def first_heading(path: Path) -> str:
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                return stripped.lstrip("#").strip()
    except OSError:
        pass
    return "Machine-readable contract or support file"


def language_for(path: Path) -> str:
    if path.name == ".env.example":
        return "dotenv"
    return {
        ".json": "json",
        ".yaml": "yaml",
        ".yml": "yaml",
        ".sql": "sql",
        ".py": "python",
        ".txt": "text",
        ".example": "dotenv",
    }.get(path.suffix.lower(), "text")


def build_master(files: list[Path]) -> None:
    lines: list[str] = [
        "# SerialOS「连载工坊」Codex 完整实现规格",
        "",
        "版本：1.0",
        "日期：2026-07-12",
        "状态：MVP implementation-ready specification",
        "",
        "> 本文件由 `scripts/build_handoff.py` 从模块化规格生成。实施时以仓库内原始文件为机器合同，",
        "> 本合并版用于通读、评审和归档。任何修改应先落到对应原文件，再重新生成本文件。",
        "",
        "## 使用方式",
        "",
        "1. Codex 从仓库根目录读取 `START_HERE.md` 和 `AGENTS.md`。",
        "2. 首次只规划 `tasks/E00-foundation.md`，不要并行实现后续 Epic。",
        "3. OpenAPI、JSON Schema 与 SQL 草案是实现边界，不得用 UI 或 Prompt 绕过。",
        "4. 每个 Epic 先形成符合 `PLANS.md` 的执行计划，再实现、验证和人工接受。",
        "",
        "## 合并内容索引",
        "",
    ]

    for index, path in enumerate(files, start=1):
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"{index}. `{rel}`：{first_heading(path)}")

    for index, path in enumerate(files, start=1):
        rel = path.relative_to(ROOT).as_posix()
        raw_content = path.read_text(encoding="utf-8", errors="replace")
        content = "\n".join(line.rstrip() for line in raw_content.splitlines()).rstrip()
        digest = sha256(path)
        lines.extend(
            [
                "",
                "---",
                "",
                f'<a id="source-{index}"></a>',
                f"# Source {index}: `{rel}`",
                "",
                f"SHA-256: `{digest}`",
                f"Bytes: `{path.stat().st_size}`",
                "",
            ]
        )
        if path.suffix.lower() == ".md":
            lines.append(content)
        else:
            fence = "````"
            lines.extend([f"{fence}{language_for(path)}", content, fence])

    (ROOT / "MASTER_SPEC.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def build_manifest() -> None:
    files = [
        path
        for path in ROOT.rglob("*")
        if path.is_file() and not is_ignored(path) and path.name != "FILE_MANIFEST.md"
    ]
    files = sorted(files, key=lambda path: path.relative_to(ROOT).as_posix())
    by_top: dict[str, list[Path]] = {}
    for path in files:
        rel = path.relative_to(ROOT)
        top = rel.parts[0] if len(rel.parts) > 1 else "root"
        by_top.setdefault(top, []).append(path)

    lines = [
        "# SerialOS File Manifest",
        "",
        "Generated by `scripts/build_handoff.py`.",
        "",
        "## Summary",
        "",
        f"- Files listed: {len(files)}",
        f"- Total bytes: {sum(path.stat().st_size for path in files)}",
        "- Hash algorithm: SHA-256",
        "",
    ]
    for group, group_files in sorted(by_top.items()):
        lines.extend([f"## `{group}`", "", "| File | Bytes | SHA-256 | Purpose |", "|---|---:|---|---|"])
        for path in group_files:
            rel = path.relative_to(ROOT).as_posix()
            purpose = first_heading(path).replace("|", "\\|")
            lines.append(f"| `{rel}` | {path.stat().st_size} | `{sha256(path)}` | {purpose} |")
        lines.append("")

    (ROOT / "FILE_MANIFEST.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    files = source_files()
    build_master(files)
    build_manifest()
    print(f"Built MASTER_SPEC.md from {len(files)} source files")
    print("Built FILE_MANIFEST.md")


if __name__ == "__main__":
    main()
